[package]
name = 'FlashPoolCoins'
version = '1.0.0'

[addresses]
flashpoolcoins = "0xc601f58f26a20e04874d456028db57c47aca73b947385d4cb30100d949f1a712"


[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
